---
title: "Censored quantile regression with partially functional effects"
author: "Stephen Lauer & Emily Peterson"
date: "April 28, 2017"
output:
    beamer_presentation:
        includes:
            in_header: slide-numbers.tex
---
### Overall Purpose

- Quantile regression offers felxibility in assessing covariate effects on event times.
- Develop quantile regression approach for survival subject to conditionally independent censoring.
-Tailor regression to partially functional effect setting. (Both varying and constant effects) 
- Martingale based estimating equations lead to single algorithm that invovles minimizing L1-type convex functions.
- Establish properties of estimators.


## Background on quantile regression

- Each covariate effect varies by quantile.
- For event time of interest $Y$ and covariate vector $W$, a quantile regression model assumes the $\tau$th quantile of $Y$ is given by:

$$
\begin{aligned}
Q_{Y}(\tau)&= F^{-1}_{Y}(\tau)\equiv \inf \{y: F_{Y}(y)\geq \tau\}, \quad \tau\in(0,1) \\
Q_{Y}(\tau|W)&= W^{T}\beta(\tau)
\end{aligned}
$$

- $Q_{Y}(\tau|W) \equiv inf{y: pr(Y \leq y | W) \geq \tau}$ denotes $\tau$th conditional quantile of $Y$ given $W$.
- Describes linear relationship between $W$ and $\tau$th quantile.
- Quantile function is minimum value of time $T$ below which subject will fall $p\times 100$ percent of times.

## Partially functional effects
- $\beta(\tau)$ represents effect of $W$ on $Q_{Y}(\tau|W)$
- Coefficients for $W$ are allowed to be function of $\tau$ meaning they are allowed to be related to both shape and location of distribution, not just a measure of central tendency.
- Partially Function Effects:
    - A model which includes a mixture of constant and varying effects.
    - $\tau$-varying coefficients correspond to effects allowed to vary by quantile group. 
- May be preferred to fully functional model due to more accurate quantile prediction for small $\tau$



## Censored quantile regression
Let $T$ and $C$ denote survival and censoring time.

$X = \min(T,C)$ and $\delta = I(T \leq C)$ where $I(\cdot)$ is indicator function.

$Y = \log T$

Partition $W$ into constant and quantile varying effects
$$
W=(Z^{T}, V^{T})^{T}
$$

$Z$ is $p\times 1$ vector of $\tau$ varying effects.

$V$ is $q\times 1$ vector of constant effects.

Data: $\{(X_{i}, \delta_{i}, Z_{i}, V_{i}),\quad i=1,...,n\}$

\textbf{Reminder:}

(a) CDF: $F_{T}(t|Z,V)= \Pr(T \leq t|Z,V)$
(b) Survival Function: $S(t)= Pr(T\geq t|Z,V) = 1-F_{T}(t|Z,V)$
(c) Cumulative Hazard Function: $\Lambda(t)= -\log S(t)= -\log (1-F_{T}(t|Z,V))$

## Partially functional quantile regression model

$$
Q_{Y}(\tau|Z,V) = Z^{T}\beta(\tau) + V^{T}\gamma, \quad \tau \in (0,1)
$$

- How do we account for the censoring?
- Monotone profile estimating equation!

## Martingale process
- To estimate $\beta(\tau)$, idea is to use stochastic property of martingale. 
- One jump counting process: gives information about when events occur. i.e. If person $i$ is "failure" by time $t$.
$$
N_{i}(t)= I(X_{i}\leq t, \delta_{i}=1)
$$

- Indicator if survival/censored time is above/equal to $t$
$$
Y_{i}(t)= I(X_{i}\geq t)
$$

- Martingale counting process wrt $F_{t}$, given by $M(t)= N(t)-\Lambda(t)$
$$M(t) = N(t) -\int_{0}^{t} Y(s)d\Lambda_{T}(s|Z,V)$$




- Non-decreasing step function minus a compensator (Cumulative Hazard Function)

- Mean-zero white noise
$$
E[M(t)|V,Z]=0
$$
    

## Estimating equation (Peng \& Huang, 2008)

- Approach for random censoring is to extend the Martingale representation of the Nelson-Aalen estimator of cumulative hazard to produce an estimating equation.
- Aim: to get $\beta$ and $\gamma$. 

- NA estimator: non-parametric estimator of the cumulative hazard rate function in case of censored data given by 
$$\tilde{H}(t)= \sum_{t_i \leq t}\frac{d_i}{n_i}$$
\noindent
with $d_i$ denote number of events at $t_i$ and $n_i$ is total number at risk at $t_i$. 



## The Estimating equation
$$
\begin{split}
    \text{E} \Bigg [ n^{-1/2}\sum_{i=1}^{n}\omega_{i} \bigg (N_{i} \exp \{Z_{i}^{T} \beta_{0} (\tau) + V_{i}^{T}\gamma_{0}\} - \\ \int_{0}^{\tau} I \Big [X_{i} \geq \exp \{Z_{i}^{T} \beta_{0} (u) + V_{i}^{T}\gamma_{0}\} \Big ] dH(u) \bigg ) \Bigg ] \\ = 0
\end{split}
$$

- $\beta_{0}$ and $\gamma_{0}$ are true values of $\beta$ and $\gamma$.
- Indicator $= \Lambda_{i}[\exp \{Z_{i}^{T} \beta_{0} (\tau) + V_{i}^{T} \gamma_{0} \}]$

## Computing Algorithm
- Step 1: Get $\hat{\beta}(\tau_{j}, \gamma)$ with $\gamma$ fixed.

$$
\begin{split}
n^{-1} \sum_{i=1}^{n} Z_{i} \Bigg ( N_{i} \exp \{Z_{i}^{T} \hat{\beta}(\tau_{j}) + V_{i}^{T}\gamma\} - \\
\sum_{k=0}^{j-1} I \bigg [X_{i} \geq \exp \{Z_{i}^{T} \hat{\beta} (\tau_k, \gamma) + V_{i}^{T} \gamma)\} \bigg ] \Big ( H(\tau_{k+1}) - H(\tau_k) \Big) \Bigg) \\
=0
\end{split}
$$

Solve for $\beta(\tau_j)$

## Computing Algorithm 
- Step 2: Get $\hat{\gamma}$ with $\hat{\beta}(\tau_j)$ fixed.
$$
\begin{split}
n^{-1} \sum_{i=1}^{n} V_{i} \Bigg( N_{i} \exp \{ Z_{i}^{T} \hat{\beta}(\tau_{j}) + V_{i}^{T} \gamma \} - \\
\sum_{k=0}^{L-1} I \bigg [X_{i} \geq \exp \{Z_{i}^{T} \hat{\beta} (\tau_k, \gamma) + V_{i}^{T} \gamma \} \bigg ] \Big (H(\tau_{k+1})-H(\tau_k ) \Big) \Bigg ) \\
=0
\end{split}
$$

Solve for $\gamma$

- Step 3...

Iterate until convergence criteria is met.


## L1-type Optimization
- Finds roots of equations via optimization techniques
- Accomplished by linear programming techniques to get $\hat{\beta}$ and $\hat{\gamma}$ that minimizes function.
+ Step 1: Set $m=0$ and choose initial $\hat{\gamma}^{m}$
+ Step 2: Find $\hat{\beta}^{(m)}(\tau_j, \hat{\gamma}^{(m)})$
\[l_{j}(h)= \sum_{i=1}^{n}|\delta_i (log X_i - V_{i}^{T}\hat{\gamma}^{(m)}-Z_{i}^{T}h)| + |R^{*}-\sum_{l=1}^{n}(-\delta_{l}Z_{l}^{T}h)|\]
\[+|R^{*}- \sum_{r=1}^{n}(2Z_{r}^{T}h\sum_{k=0}^{j-1}I[X_r \geq exp{Z_{i}^{T}\hat{\beta}^{(m)}+V_{i}^{T}\hat{\gamma}^{(m)}}]\]
\[{H(\tau_{k+1})- H(\tau_k)})|\]


##
+ Step 3: Find $\hat{\gamma}^{(m+1)}$ given estimate for $\beta^{(m)}$ from step 2.
\[l^{*}(h)= \sum_{i=1}^{n}|\delta_i (log X_i - Z_{i}^{T}\hat{\beta}^{(m)}-V_{i}^{T}h)| + |R^{*}-\sum_{l=1}^{n}(-\delta_{l}V_{l}^{T}h)|\]
\[+\sum_{k=0}^{L-1}[\sum_{i=1}^{n}|{logX_i-Z_{i}^{T}\hat{\beta}^{(m)}-V_{i}^{T}h}{H(\tau_{k+1}-H(\tau_k )}|\]
\[+|R^{*}-\sum_{r=1}^{n}(-V_{r}^{T}h){H(\tau_{k+1})-H(\tau_k )}|\]
\[+|R^{*}-\sum_{s=1}^{n}2V_{s}^{T}hH(\tau_L )|\]

+ Step 4: Update $m$ to $m+1$ and repeat steps 2-3 until convergence criteria met.





## Asymptotic Properties

- Theorem 1:  Shows consistency, as $n\rightarrow \infty$, estimates converge to the truth, so they are \textbf{unbiased} estimators.
$$\hat{\gamma}\rightarrow \gamma_0 \mbox { in probability }$$
$$ sup||\hat{\beta}(\tau)-\beta_0 (\tau)||\rightarrow 0 \mbox{ in probability }$$

- Theorem 2: Asymptotic Distributions
$$n^{1/2}(\hat{\gamma}- \gamma_0 )\sim^{\mathrm{asymp}}N(0, E[...])$$
$$n^{1/2}(\hat{\beta}(\tau)- \beta_0(\tau))\rightarrow GT(\tau)$$
+ Generalizatin of asymptotic normality for parameter that is function of $\tau$. 


## Resampling-based inference procedure



## Simulation study: overview

Simulations were conducted to assess the finite-sample performace of the proposed method versus the Peng-Huang estimator in the following metrics:

- bias
- variance
- computing time, as well as
- the impact of varying the following parameters on estimator efficiency:
    - sample size
    - number of covariates
    - dependency among covariates
    - censoring proportion
    - error heteroscedasticity
    
(Could look across the 2 sims in main paper or across 5 experiments in supplement)

## Simulation study: Setup I

$$
\begin{aligned}
    \log T &= b_1 V_1 + b_2 V_2 + \epsilon \\
    \epsilon &\sim \text{extreme value (?)} \\
    V_1 &\sim Uniform(0,1) \\
    V_2 &\sim Bernoulli(0.5) \\
    b_1 &: {0,0.5} \\
    b_2 &= -0.5 \\
    C &\sim Uniform(0.1I(Z_1=1),c_u) \\
    c_u &= 
    \begin{cases}
        3.8 & \quad \text{when } b_1=0.5 \\
        5 & \quad \text{when } b_1=0 \\
    \end{cases}
\end{aligned}
$$

## Simulation study: Setup I (cont.)

Partially functional quantile regression model:

$$
\begin{aligned}
    Q_{Y}(\tau|Z,V) &= Z^{T}\beta(\tau) + V^{T}\gamma, \quad \tau \in (0,1) \\
    Z &= 1 \\
    V &= (V_1, V_2)^T \\
    \beta_0(\tau) &= Q_\epsilon(\tau) \\
    \gamma_0 &\equiv (\gamma_{01},\gamma_{02})^T = (b_1, b_2)^T
\end{aligned}
$$

## Case study: renal disease

- A prospective study to investigate the risk factors in a cohort of 191 incidnt dialysis patients recruited from 26 facilities
- 35% of survival times censored due to renal transplant or the end of the study
- Covariates:
    - Patient age
    - Fish consumption in first year of dialysis (1 if any, 0 o.w.)
    - Baseline dialysis modality (1 if hemodialysis, 0 o.w.)
    - Education level (1 if high school or higher, 0 o.w.)
    - Race (1 if black, 0 o.w.)
    - Severe restless leg symptoms (1 if present, 0 o.w.)

## Discussion